"""Auditable AS-IS documentation generated by the exploration phase.

This module deliberately stops at discovery.  It produces the business and
technical dossier that a bank can review before *any* TO-BE or migration work
is allowed to start.
"""
from __future__ import annotations

import csv
import json
import re
import shutil
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from work_items import inventory_source


_COPY_RE = re.compile(r"^\s*COPY\s+([A-Z0-9-]+)", re.IGNORECASE | re.MULTILINE)
_FILE_RE = re.compile(r"^\s*(SELECT|OPEN|READ|WRITE|REWRITE|CLOSE)\b", re.IGNORECASE | re.MULTILINE)
_SQL_RE = re.compile(r"EXEC\s+SQL", re.IGNORECASE)
_CICS_RE = re.compile(r"EXEC\s+CICS", re.IGNORECASE)
_BATCH_RE = re.compile(r"\b(SORT|JCL|JOB|SYSIN)\b", re.IGNORECASE)
_CORPUS_EXCLUDED = {".git", ".venv", "node_modules", "dist", "migration-state", ".codebase-memory", "docs-cobol-accounting-system"}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def prepare_repository_corpus(repository_root: Path, corpus_dir: Path) -> dict[str, int]:
    """Create a read-only analysis snapshot of the complete repository.

    Archives are expanded under the snapshot so Claude Code can inspect their
    contents with Read rather than silently treating a ZIP as an opaque file.
    Generated/build directories are excluded and reported in the manifest.
    """
    if corpus_dir.exists():
        shutil.rmtree(corpus_dir)
    corpus_dir.mkdir(parents=True)
    copied = expanded = 0
    for source in repository_root.rglob("*"):
        relative = source.relative_to(repository_root)
        if any(part in _CORPUS_EXCLUDED for part in relative.parts) or not source.is_file():
            continue
        target = corpus_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        copied += 1
        if source.suffix.lower() != ".zip":
            continue
        try:
            with zipfile.ZipFile(source) as archive:
                destination = corpus_dir / "__expanded_archives__" / source.stem
                for member in archive.infolist():
                    name = Path(member.filename)
                    if member.is_dir() or name.is_absolute() or ".." in name.parts:
                        continue
                    archive_target = destination / name
                    archive_target.parent.mkdir(parents=True, exist_ok=True)
                    with archive.open(member) as origin, archive_target.open("wb") as sink:
                        shutil.copyfileobj(origin, sink)
                    expanded += 1
        except zipfile.BadZipFile:
            continue
    (corpus_dir / "CORPUS-MANIFEST.json").write_text(json.dumps({
        "repository_root": str(repository_root), "files_copied": copied,
        "archive_members_expanded": expanded, "excluded_directories": sorted(_CORPUS_EXCLUDED),
    }, indent=2), encoding="utf-8")
    return {"files_copied": copied, "archive_members_expanded": expanded}


def _lines(text: str, needle: str) -> list[int]:
    """Return every 1-based source line containing ``needle`` (case-insensitive)."""
    token = needle.casefold()
    return [number for number, line in enumerate(text.splitlines(), 1) if token in line.casefold()]


def _anchor(path: str, lines: list[int]) -> str:
    return f"{path}:{lines[0]}" if lines else f"{path}:unknown"


def _slug(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "-", value.upper()).strip("-") or "ITEM"


def _evidence_for_rule(source_dir: Path, rule: dict[str, Any], fallback_path: str) -> list[str]:
    """Keep only anchors that resolve to a real source line.

    Agent output is evidence, not authority: an unresolvable citation is not
    published as a fact.  A deterministic fallback points reviewers to the
    program where the candidate was found.
    """
    verified: list[str] = []
    for raw in rule.get("anchors", []):
        if not isinstance(raw, str) or ":" not in raw:
            continue
        path, marker = raw.split(":", 1)
        candidate = source_dir / path
        if not candidate.is_file():
            continue
        text = candidate.read_text(errors="replace")
        if marker.isdigit() and 0 < int(marker) <= len(text.splitlines()):
            verified.append(f"{path}:{marker}")
        elif marker and marker != "unknown" and _lines(text, marker):
            verified.append(_anchor(path, _lines(text, marker)))
    if verified:
        return sorted(set(verified))
    candidate = source_dir / fallback_path
    return [_anchor(fallback_path, [1] if candidate.is_file() else [])]


def _source_facts(source_dir: Path, pack: dict[str, Any]) -> dict[str, Any]:
    files = inventory_source(source_dir)
    programs = {p.get("path"): p for p in pack.get("programs", [])}
    facts: list[dict[str, Any]] = []
    for file in files:
        text = (source_dir / file.path).read_text(errors="replace")
        facts.append({
            "path": file.path,
            "kind": file.kind,
            "program_id": programs.get(file.path, {}).get("program_id") or file.program_id,
            "loc": file.loc,
            "copybooks": _COPY_RE.findall(text),
            "file_operations": _FILE_RE.findall(text),
            "sql": bool(_SQL_RE.search(text)),
            "cics": bool(_CICS_RE.search(text)),
            "batch": bool(_BATCH_RE.search(text)),
            "text": text,
        })
    return {"files": facts}


def _markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    header = "| " + " | ".join(headers) + " |"
    delimiter = "| " + " | ".join("---" for _ in headers) + " |"
    return "\n".join([header, delimiter, *("| " + " | ".join(row) + " |" for row in rows)])


def build_documentation_manifest(source_dir: Path, pack: dict[str, Any]) -> dict[str, Any]:
    """Create an evidence-first manifest for the Tier 1/2 AS-IS dossier."""
    facts = _source_facts(source_dir, pack)
    programs = pack.get("programs", [])
    rules: list[dict[str, Any]] = []
    risks: list[dict[str, Any]] = []
    questions: list[dict[str, Any]] = []
    sequence = 1
    for module in pack.get("modules", []):
        member_paths = module.get("member_paths", [])
        fallback_path = member_paths[0] if member_paths else "unknown"
        for candidate in module.get("business_rules", []):
            text = str(candidate.get("text", "")).strip()
            if not text:
                continue
            rule_id = f"BR-{sequence:03d}"
            sequence += 1
            evidence = _evidence_for_rule(source_dir, candidate, fallback_path)
            rules.append({
                "id": rule_id,
                "text": text,
                "evidence": evidence,
                "confidence": "candidate" if candidate.get("source") == "agent" else "draft",
                "validation_status": "pending",
                "module_id": module.get("module_id"),
            })
        for risk_text in module.get("risks", []):
            risks.append({"id": f"RSK-{len(risks)+1:03d}", "text": risk_text, "module_id": module.get("module_id")})
        if module.get("human_notes"):
            questions.append({"id": f"QA-{len(questions)+1:03d}", "text": module["human_notes"], "module_id": module.get("module_id"), "status": "open"})

    for fact in facts["files"]:
        for copybook in fact["copybooks"]:
            risks.append({"id": f"RSK-{len(risks)+1:03d}", "text": f"COPY dependency {copybook} requires expansion review", "module_id": None})
        if fact["sql"] or fact["cics"] or fact["file_operations"]:
            questions.append({
                "id": f"QA-{len(questions)+1:03d}", "module_id": None, "status": "open",
                "text": f"Confirm runtime ownership and operational contract for {fact['path']} integrations/I-O.",
            })
    return {"generated_at": _now(), "programs": programs, "facts": facts, "rules": rules, "risks": risks, "questions": questions}


def write_as_is_documentation(output_dir: Path, source_dir: Path, pack: dict[str, Any]) -> dict[str, Any]:
    """Write the Tier 1/2 dossier and return its machine-readable manifest.

    The resulting directory is intentionally independent from the example
    dossier supplied by the user. Each run owns its documentation snapshot.
    """
    manifest = build_documentation_manifest(source_dir, pack)
    output_dir.mkdir(parents=True, exist_ok=True)
    trace_dir = output_dir / "00-trazabilidad"
    functional_dir = output_dir / "01-funcional"
    technical_dir = output_dir / "02-tecnico"
    for directory in (trace_dir, functional_dir, technical_dir):
        directory.mkdir(exist_ok=True)

    program_rows = [[str(p.get("program_id") or "—"), str(p.get("path")), str(p.get("loc", 0)), str(p.get("complexity_tier", "LOW"))] for p in manifest["programs"]]
    rule_rows = [[r["id"], r["text"], ", ".join(r["evidence"]), r["confidence"], r["validation_status"]] for r in manifest["rules"]]
    question_rows = [[q["id"], q["text"], q["status"]] for q in manifest["questions"]]
    integration_rows = [[f["path"], "SQL" if f["sql"] else "CICS" if f["cics"] else "File I/O" if f["file_operations"] else "None", "review required" if (f["sql"] or f["cics"] or f["file_operations"]) else "none detected"] for f in manifest["facts"]["files"]]

    (output_dir / "README.md").write_text(
        "# Dossier AS-IS de exploración\n\n"
        "Este paquete es el primer entregable del flujo: describe lo que el código COBOL evidencia hoy. "
        "No contiene diseño TO-BE ni artefactos de migración. Toda conclusión debe conservar su evidencia y ser validada por negocio antes de convertirse en requisito.\n\n"
        "## Contenido\n\n"
        "- `01-funcional`: reglas, procesos, glosario y preguntas abiertas.\n"
        "- `02-tecnico`: inventario, datos, dependencias, integraciones, batch, diagramas y riesgos.\n"
        "- `00-trazabilidad`: registro auditable de evidencias.\n",
        encoding="utf-8",
    )
    (trace_dir / "esquema-de-ids.md").write_text(
        "# Esquema de identificadores y trazabilidad\n\n"
        "Los IDs son inmutables. `PGM-` identifica programas, `DAT-` campos, "
        "`UC-` casos de uso, `BR-` reglas, `RSK-` riesgos y `QA-` preguntas. "
        "Toda afirmación debe apuntar a archivo y línea; una regla pendiente no "
        "autoriza cambios de migración.\n",
        encoding="utf-8",
    )
    (functional_dir / "01-catalogo-de-reglas-de-negocio.md").write_text("# Catálogo de reglas de negocio\n\n" + _markdown_table(["ID", "Regla candidata", "Evidencia", "Confianza", "Validación banco"], rule_rows or [["—", "No se extrajeron reglas", "—", "—", "—"]]) + "\n", encoding="utf-8")
    (functional_dir / "02-procesos-y-casos-de-uso.md").write_text("# Procesos y casos de uso\n\n" + _markdown_table(["Módulo", "Punto de entrada", "Programas"], [[m.get("title", m.get("module_id", "—")), m.get("entrypoint_path", "—"), ", ".join(m.get("source_program_ids", []))] for m in pack.get("modules", [])] or [["—", "—", "—"]]) + "\n\nLos flujos son candidatos derivados del grafo estático; requieren validación funcional.\n", encoding="utf-8")
    # Real bug found live: same class as the data-dictionary stub above —
    # data_dictionary is now attached to the pack, so build the glossary
    # from it instead of publishing "no data attached" prose.
    glossary_rows = [
        [d.get("name", "—"), d.get("pic", "—"), d.get("path", "—"), ", ".join(d.get("tags", [])) or "—"]
        for d in pack.get("data_dictionary", [])
    ]
    (functional_dir / "03-glosario-de-negocio.md").write_text(
        "# Glosario de negocio\n\n" + _markdown_table(
            ["Término", "PIC", "Archivo", "Notas"],
            glossary_rows or [["—", "—", "—", "No se detectaron campos WORKING-STORAGE"]],
        ) + "\n\nLos términos son los campos WORKING-STORAGE tal como aparecen en el código; "
            "ninguna semántica de negocio se infiere sin evidencia adicional.\n",
        encoding="utf-8",
    )
    (functional_dir / "04-preguntas-abiertas.md").write_text("# Preguntas abiertas y comportamiento no documentado\n\n" + _markdown_table(["ID", "Pregunta", "Estado"], question_rows or [["—", "No se detectaron preguntas automáticamente; revisión humana pendiente.", "open"]]) + "\n", encoding="utf-8")
    repository_rows = [[str(f.get("program_id") or "—"), str(f.get("path")), str(f.get("kind")), str(f.get("loc", 0))] for f in manifest["facts"]["files"]]
    (technical_dir / "05-inventario-y-catalogo-de-programas.md").write_text(
        "# Inventario y catálogo del repositorio\n\n"
        "El alcance de exploración incluye todos los archivos entregados (código, UI, diseño, configuración, scripts, documentación y archivos archivados expandidos). La migración posterior, si se autoriza, se limita al backend COBOL.\n\n"
        "## Programas COBOL\n\n" + _markdown_table(["PROGRAM-ID", "Archivo", "LOC", "Complejidad"], program_rows or [["—", "—", "0", "—"]]) +
        "\n\n## Inventario completo de archivos\n\n" + _markdown_table(["PROGRAM-ID", "Archivo", "Tipo", "LOC"], repository_rows or [["—", "—", "—", "0"]]) + "\n",
        encoding="utf-8",
    )
    # Real bug found live (user: "solo dejas un placeholder"): this used to
    # be a hardcoded stub string. parse_structural() already extracts
    # name/PIC/tags per field (exploration_core.build_exploration_pack now
    # attaches it to the pack as data_dictionary) — render it for real.
    dictionary_rows = [
        [d.get("name", "—"), d.get("pic", "—"), d.get("path", "—"), ", ".join(d.get("tags", [])) or "—"]
        for d in pack.get("data_dictionary", [])
    ]
    (technical_dir / "06-diccionario-de-datos.md").write_text(
        "# Diccionario de datos\n\n" + _markdown_table(
            ["Campo", "PIC", "Archivo", "Notas"],
            dictionary_rows or [["—", "—", "—", "No se detectaron campos WORKING-STORAGE"]],
        ) + "\n\nExtraído deterministamente de las cláusulas PIC en WORKING-STORAGE; "
            "no infiere semántica de negocio sin evidencia adicional.\n",
        encoding="utf-8",
    )
    edge_rows = [[e["from_path"], e["to_path"], e.get("edge_type", "CALL"), e.get("target_program_id", "—")] for e in pack.get("call_graph_resolved", {}).get("edges", [])]
    (technical_dir / "07-mapa-de-dependencias.md").write_text("# Mapa de dependencias\n\n" + _markdown_table(["Origen", "Destino", "Tipo", "Objetivo"], edge_rows or [["—", "—", "—", "Sin llamadas resueltas"]]) + "\n\nDependencias no resueltas:\n\n" + "\n".join(f"- {item['text']}" for item in pack.get("open_items", [])) + "\n", encoding="utf-8")
    (technical_dir / "08-inventario-de-integraciones.md").write_text("# Inventario de integraciones\n\n" + _markdown_table(["Archivo", "Tipo detectado", "Estado"], integration_rows or [["—", "—", "—"]]) + "\n", encoding="utf-8")
    batch_rows = [[f["path"], "candidate" if f["batch"] else "none detected"] for f in manifest["facts"]["files"]]
    (technical_dir / "09-catalogo-de-procesos-batch.md").write_text("# Catálogo de procesos batch\n\n" + _markdown_table(["Archivo", "Señal batch"], batch_rows or [["—", "none detected"]]) + "\n", encoding="utf-8")
    mermaid_edges = "\n".join(f'    "{e["from_path"]}" --> "{e["to_path"]}"' for e in pack.get("call_graph_resolved", {}).get("edges", [])) or "    Empty[No resolved CALL edges]"
    (technical_dir / "10-diagramas-as-is.md").write_text(f"# Diagramas AS-IS\n\n## Grafo de llamadas\n\n```mermaid\ngraph TD\n{mermaid_edges}\n```\n", encoding="utf-8")
    risk_rows = [[r["id"], r["text"], r.get("module_id") or "estate", "pending review"] for r in manifest["risks"]]
    (technical_dir / "11-evaluacion-de-complejidad-y-riesgo.md").write_text("# Complejidad y riesgo\n\n" + _markdown_table(["ID", "Hallazgo", "Ámbito", "Estado"], risk_rows or [["—", "No se detectaron riesgos por las reglas actuales", "estate", "pending review"]]) + "\n", encoding="utf-8")

    trace_path = trace_dir / "registro-trazabilidad.csv"
    with trace_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["id", "tipo", "descripcion", "archivo_fuente", "linea_inicio", "linea_fin", "metodo_verificacion", "artefacto_to_be", "estado_validacion", "validado_por", "fecha_validacion"])
        writer.writeheader()
        for rule in manifest["rules"]:
            evidence = rule["evidence"][0].split(":", 1) if rule["evidence"] else ["", ""]
            writer.writerow({"id": rule["id"], "tipo": "regla_negocio", "descripcion": rule["text"], "archivo_fuente": evidence[0], "linea_inicio": evidence[1], "linea_fin": evidence[1], "metodo_verificacion": "lectura_codigo", "artefacto_to_be": "", "estado_validacion": rule["validation_status"], "validado_por": "", "fecha_validacion": ""})
        for risk in manifest["risks"]:
            writer.writerow({"id": risk["id"], "tipo": "riesgo", "descripcion": risk["text"], "archivo_fuente": "", "linea_inicio": "", "linea_fin": "", "metodo_verificacion": "lectura_codigo", "artefacto_to_be": "", "estado_validacion": "pending", "validado_por": "", "fecha_validacion": ""})
        for question in manifest["questions"]:
            writer.writerow({"id": question["id"], "tipo": "pregunta_abierta", "descripcion": question["text"], "archivo_fuente": "", "linea_inicio": "", "linea_fin": "", "metodo_verificacion": "", "artefacto_to_be": "", "estado_validacion": question["status"], "validado_por": "", "fecha_validacion": ""})
    nodes: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    for index, program in enumerate(manifest["programs"]):
        node_id = f"program:{program.get('path')}"
        nodes.append({"id": node_id, "label": program.get("program_id") or program.get("path"), "kind": "program", "x": 90 + index * 210, "y": 110, "evidence": [f"{program.get('path')}:1"]})
    for index, rule in enumerate(manifest["rules"]):
        node_id = rule["id"]
        nodes.append({"id": node_id, "label": rule["text"][:72], "kind": "rule", "x": 90 + (index % 4) * 210, "y": 300 + (index // 4) * 110, "evidence": rule["evidence"]})
        source_path = rule["evidence"][0].split(":", 1)[0] if rule["evidence"] else None
        if source_path:
            edges.append({"source": f"program:{source_path}", "target": node_id, "kind": "evidence", "evidence": rule["evidence"]})
    for index, risk in enumerate(manifest["risks"]):
        nodes.append({"id": risk["id"], "label": risk["text"][:72], "kind": "risk", "x": 980, "y": 110 + index * 100, "evidence": []})
    for index, question in enumerate(manifest["questions"]):
        nodes.append({"id": question["id"], "label": question["text"][:72], "kind": "question", "x": 980, "y": 450 + index * 100, "evidence": []})
    (output_dir / "documentation_graph.json").write_text(
        json.dumps({"schema": 1, "generated_by": "deterministic_fallback", "nodes": nodes, "edges": edges}, indent=2),
        encoding="utf-8",
    )
    return {"root": str(output_dir), "manifest": manifest, "documents": sorted(str(p.relative_to(output_dir)) for p in output_dir.rglob("*") if p.is_file())}


def validate_as_is_documentation(output_dir: Path, source_dir: Path, required_documents: list[str]) -> list[str]:
    """Return closure errors; an agent-produced dossier is never trusted blindly."""
    errors = [f"missing document: {path}" for path in required_documents if not (output_dir / path).is_file()]
    trace_path = output_dir / "00-trazabilidad" / "registro-trazabilidad.csv"
    if not trace_path.is_file():
        return errors + ["missing traceability CSV"]
    graph_path = output_dir / "documentation_graph.json"
    try:
        graph = json.loads(graph_path.read_text(encoding="utf-8"))
        if not isinstance(graph.get("nodes"), list) or not isinstance(graph.get("edges"), list):
            errors.append("documentation graph has no nodes or edges lists")
    except (OSError, json.JSONDecodeError):
        errors.append("documentation graph is invalid JSON")
    with trace_path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    required_columns = {"id", "tipo", "archivo_fuente", "linea_inicio", "linea_fin", "metodo_verificacion", "estado_validacion"}
    if not rows or not required_columns.issubset(set(rows[0])):
        return errors + ["traceability CSV does not implement the required contract"]
    ids = [row.get("id", "") for row in rows]
    if any(not item for item in ids) or len(ids) != len(set(ids)):
        errors.append("traceability IDs are empty or duplicated")
    for row in rows:
        source = row.get("archivo_fuente", "").strip()
        if not source:
            continue
        candidate = source_dir / source
        if not candidate.is_file():
            errors.append(f"trace source missing: {source}")
            continue
        count = len(candidate.read_text(errors="replace").splitlines())
        for field in ("linea_inicio", "linea_fin"):
            value = row.get(field, "").strip()
            if not value.isdigit() or not 0 < int(value) <= count:
                errors.append(f"invalid {field} for {row.get('id')}: {source}:{value}")
    return errors
